name: video-processing-api
region: nyc
services:
  - name: api
    github:
      repo: yourusername/VideoProcessingApp-Deployment
      branch: main
      deploy_on_push: false
    dockerfile_path: VideoProcessingApp/Dockerfile
    source_dir: VideoProcessingApp
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    envs:
      - key: SPACES_ACCESS_KEY
        scope: RUN_TIME
        value: ${SPACES_ACCESS_KEY}
        type: SECRET
      - key: SPACES_SECRET_KEY
        scope: RUN_TIME
        value: ${SPACES_SECRET_KEY}
        type: SECRET
      - key: SPACES_BUCKET
        scope: RUN_TIME
        value: ${SPACES_BUCKET}
      - key: SPACES_ENDPOINT
        scope: RUN_TIME
        value: ${SPACES_ENDPOINT}
      - key: WEBHOOK_SECRET
        scope: RUN_TIME
        value: ${WEBHOOK_SECRET}
        type: SECRET
      - key: ASPNETCORE_ENVIRONMENT
        scope: RUN_TIME
        value: Production
    health_check:
      http_path: /health
    cors:
      allow_origins:
        - "https://yourusername.github.io"
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
      expose_headers:
        - Content-Length
        - Content-Type
      max_age: 86400
